print("money_constants.py being imported - start")



TYPICAL_STARTING_PRICE = 2.0



ITERATIONS_PER_DAY = 1000
NUM_AGENTS = 30
NUM_AGENTS_FOR_PRICE_COMPARISON = 3      # i.e. we purchase from cheapest of N others
TYPICAL_GOODS_MADE_PER_DAY = 10.0
MAXIMUM_STOCK = TYPICAL_GOODS_MADE_PER_DAY*7
TYPICAL_STARTING_MONEY = 100.0
TYPICAL_DAYS_BETWEEN_PRICE_CHANGES = 3
TYPICAL_DAYS_BETWEEN_PURCHASES = 1
UNIT_OF_GOODS = 1.0
NO_AGENT_FOUND = -1
SHOW_SALES_INFO = False
INIFINITE = 9999999

print("money_constants.py being imported - end")